### ISSUE TITLE
Modeling 1-DOF joint

### ISSUE THREAD

**Issue by waltejon** [ramaniitrgoyal92/Tensegrity_Engineering_Analysis_Master-TEAM-#10]
Hello @ramaniitrgoyal92!

First of all, a big thank you for providing your code here. I am enthusiastic and very interested in the modeling and control of tensegrity structures.

I have a question about Section 5.1 in the User Guide. Line 8 defines `s_0` within the data structure. What does this variable stand for?

In many examples, `classK_.s_0 = [1; 0.5] `. In some cases, `s_0` is also equated with the vector that is defined from the remaining length calculation (see Section 3).

In particular, I would like to model and simulate the **structure** shown below. I have four nodes, one bar and four strings, two of which are supposed to be passive and two are active (see Fig. 1).

![oneDOFJoint](https://user-images.githubusercontent.com/44841727/80013255-e3e84180-84ce-11ea-979b-dd2e23bd5ed1.jpg)

I use the script below for this. However, in `tenseg_sim_classk_open.m` leads to many ` NaN` values, see Fig. 2. I currently have the suspicion that I have parameterized something else incorrectly.

<img width="1916" alt="Anmerkung 2020-04-22 192012" src="https://user-images.githubusercontent.com/44841727/80012903-56a4ed00-84ce-11ea-93f8-0f21d20d498c.png">

---

### Used script

```
clear all; clc; close all; warning off;

% Specify initial node positions

n1              = [  0;              0;             0;  ];
n2              = [  0;              2;             0;  ];
n3              = [ -1;              1;             0;  ];
n4              = [  1;              1;             0;  ];

N_simple = [n1 n2 n3 n4];

C_b_in = [1 2];

C_s_in = [1 3;
          1 4;
          4 2;
          3 2;];

% Convert above index notation into actual connectivity matrices
C_b = tenseg_ind2C(C_b_in,N_simple);
C_s = tenseg_ind2C(C_s_in,N_simple);

% pinned_nodes
pinned_nodes = [1];

% To illustrate the class k conversion process, print the initial number of
% nodes here
disp(['Initial # of nodes: ' num2str(size(N_simple,2))])
% tenseg_plot(N_simple,C_b,C_s);

% Convert specified class k structure into a class 1 structure with constraints
[N_new,C_b_new,C_s_new,P,D,node_constraints] = tenseg_class_k_convert(N_simple,C_b,C_s,pinned_nodes);

% Print the final number of nodes
disp(['Converted Class K # of nodes:' num2str(size(N_new,2))])

% Print the generated node constraints
disp(['Class K Node constraints:'])
for i=1:numel(node_constraints)
	if numel(node_constraints{i})>1
		disp(['   Coincident nodes: ' num2str(node_constraints{i})])
	end
end
%Specify resting string lengths

% Here, we're setting every string rest length to 70% of its given length
S_0_percent = [(1:size(C_s_new,1))', 0.7*ones(size(C_s_new,1),1)]; % percent of initial lengths
S_0_percent(1, 2) = 1; % active string should have initial rest length
S_0_percent(2, 2) = 1; % active string should have initial rest length 

% This function converts those specified percentages into rest lengths
s_0 = tenseg_percent2s0(N_new,C_s_new,S_0_percent);

%% Simulation 
% Create data structure of system BEFORE segmentation
classK_test.N = N_new;
classK_test.C_b = C_b_new;
classK_test.C_s = C_s_new;
classK_test.P = P;
classK_test.D = D;
classK_test.s_0 = s_0;
classK_test.tf = 5;
classK_test.dt = .001;
classK_test.video = 0;

%%
% Perform simulation
[History,debug] = tenseg_sim_classkopen(classK_test);

%% Plotting position and velocity of specified node/axes
tenseg_plot_node(History,[1,2],[1,2,3])
tenseg_plot_velocity(History,[1,2],[1,2,3])

%% Create plots with 3D objects 
classK_test.Bradius = 0.02; % Radius of bars [# bars x 1]
classK_test.Sradius = [0.01; 0.01; 0.01; 0.01]; % Radius of strings [# strings x 1]
classK_test.Nradius = 0.035*ones(size(classK_test.N,2),1); % Radius of node spheres [# nodes x 1]

%% Plotting configurations
number_of_configurations = 3; % Number of configurations to plot
tenseg_plot_configurations(History, classK_test, number_of_configurations)

%% Create animation
% tenseg_animation(History,classK_test,[],[],[],[],10)

% save Example_class_k_Dbar.mat

```

**Comment by ramaniitrgoyal92** [comment]
Hello @waltejon !

s_0 represents the absolute rest length of the strings prescribed as a vector. 
You can directly give the rest length values
 or
 use the S_0_percent to give the % length of the strings and then use the function tenseg_percent2s0 to convert it to s_0. 


From the figure, it seems that you have pinned nodes n3 and n4, in that case, you should specify that in
pinned_nodes = [2 3];
and if all the first three nodes are pinned then passive strings do not play any role in the dynamics.

I hope it helps!

**Comment by waltejon** [comment]
@ramaniitrgoyal92 Thank you for the quick response!

- Okay, I understood the meaning of `s_0`. It is also mentioned in Section 5.2 of the user guide.

- You are right. In my setup, the nodes n3 and n4 are pinned. Due to the order in `N_simple`, I have to set `pinned_nodes = [3 4]`.

---

### Open challenge: NaN values

Despite the change in the pinned nodes, I still get `NaN` values when starting the simulation ... It seems to me that my configuration within the simulation is not stable. You will find the used script below.

If I pin all four nodes, i.e. `pinned_nodes = [1 2 3 4]`, then the system is stable and nothing moves - as expected. As soon as I only pin nodes n3 and n4 again, `NaN` values appear from step 2 and the plots remain empty (see Fig. 1).

**My expectation**

In reality, I would assume that the pinned nodes n3 and n4 and the strings towards n1 would stabilize the bar... Due to the constrained bar length, node n2 should stay in the same position if the active strings (red) have the same pre-tension or rest length.

@ramaniitrgoyal92: How would you expect the configuration's behaviour in reality and your simulation?

<img width="1525" alt="tmp" src="https://user-images.githubusercontent.com/44841727/80087685-bdbcb300-855b-11ea-895a-6c22f2bb6081.png">

---

### Used script

```
clear all; clc; close all; warning off;

% Specify initial node positions

n1 = [0 -1 0]';
n2 = [0 1 0]';
n3 = [-1 0 0]';
n4 = [1 0 0]';

N_simple = [n1 n2 n3 n4];

C_b_in = [1 2];

C_s_in = [1 3;
          1 4;
          4 2;
          3 2;];

% Convert above index notation into actual connectivity matrices
C_b = tenseg_ind2C(C_b_in,N_simple);
C_s = tenseg_ind2C(C_s_in,N_simple);

% pinned_nodes
pinned_nodes = [3 4];

% To illustrate the class k conversion process, print the initial number of
% nodes here
disp(['Initial # of nodes: ' num2str(size(N_simple,2))])
% tenseg_plot(N_simple,C_b,C_s);

% Convert specified class k structure into a class 1 structure with constraints
[N_new,C_b_new,C_s_new,P,D,node_constraints] = tenseg_class_k_convert(N_simple,C_b,C_s,pinned_nodes);

% Print the final number of nodes
disp(['Converted Class K # of nodes:' num2str(size(N_new,2))])

% Print the generated node constraints
disp(['Class K Node constraints:'])
for i=1:numel(node_constraints)
	if numel(node_constraints{i})>1
		disp(['   Coincident nodes: ' num2str(node_constraints{i})])
	end
end
%Specify resting string lengths

% Here, we're setting every string rest length to 70% of its given length
S_0_percent = [(1:size(C_s_new,1))', 0.7*ones(size(C_s_new,1),1)]; % percent of initial lengths

% This function converts those specified percentages into rest lengths
s_0 = tenseg_percent2s0(N_new,C_s_new,S_0_percent);

%% Simulation 
% Create data structure of system BEFORE segmentation
classK_test.N = N_new;
classK_test.C_b = C_b_new;
classK_test.C_s = C_s_new;
classK_test.P = P;
classK_test.D = D;
classK_test.s_0 = s_0;
classK_test.tf = 5;
classK_test.dt = .001;
classK_test.video = 0;

%%
% Perform simulation
[History,debug] = tenseg_sim_classkopen(classK_test);

%% Plotting position and velocity of specified node/axes
tenseg_plot_node(History,[1,2,3,4],[1,2,3])
tenseg_plot_velocity(History,[1,2,3,4],[1,2,3])

%% Create plots with 3D objects 
classK_test.Bradius = 0.02; % Radius of bars [# bars x 1]
classK_test.Sradius = [0.01; 0.01; 0.01; 0.01]; % Radius of strings [# strings x 1]
classK_test.Nradius = 0.035*ones(size(classK_test.N,2),1); % Radius of node spheres [# nodes x 1]

%% Plotting configurations
number_of_configurations = 3; % Number of configurations to plot
tenseg_plot_configurations(History, classK_test, number_of_configurations)

%% Create animation
% tenseg_animation(History,classK_test,[],[],[],[],10)

% save Example_class_k_Dbar.mat
```

**Comment by waltejon** [comment]
@ramaniitrgoyal92: It may also help if we focus our discussion on an even **more simplified system** (see figure below)? Again, I have the problem that `NaN` values appear from simulation step 2 (see above).

<img width="846" alt="tmp2" src="https://user-images.githubusercontent.com/44841727/80089066-b26a8700-855d-11ea-95ff-9b39a4c9b499.png">

### Objective of my activities

**Modeling**

With the help of MOTES, I would like to model and simulate that the two strings are wound and unwound. With this I want to create the rotation of the bar.

**Control**

When the modeling is fine, I would like to control this simple system. The controlled variable shall be the **force density** in the strings. In practice, we use load cells to determine the string force and then (in the future) the string force density. For the control, I would like to use the mathematics of your publication ["Model and Data Based Approaches to the Control of Tensegrity Robots"](https://ieeexplore.ieee.org/abstract/document/9031374).

@ramaniitrgoyal92:
- Do you think that MOTES support this? 
- Do I have to use these gyros I saw when I investigated the code?
- Is MOTES compatible to your another publication ["Model and Data Based Approaches to the Control of Tensegrity Robots"](https://ieeexplore.ieee.org/abstract/document/9031374)?

### Used script

```
clear all; clc; close all; warning off;


n1 = [0 0 0]';
n2 = [-1 0 0]';
n3 = [1 0 0]';
n4 = [0 2 0]';

N_simple = [n1 n2 n3 n4];

C_b_in = [1 4];

C_s_in = [2 4;
          3 4];

% Convert above index notation into actual connectivity matrices
C_b = tenseg_ind2C(C_b_in,N_simple);
C_s = tenseg_ind2C(C_s_in,N_simple);

% pinned_nodes
pinned_nodes = [1 2 3];

% To illustrate the class k conversion process, print the initial number of
% nodes here
disp(['Initial # of nodes: ' num2str(size(N_simple,2))])
% tenseg_plot(N_simple,C_b,C_s);

% Convert specified class k structure into a class 1 structure with constraints
[N_new,C_b_new,C_s_new,P,D,node_constraints] = tenseg_class_k_convert(N_simple,C_b,C_s,pinned_nodes);

% Print the final number of nodes
disp(['Converted Class K # of nodes:' num2str(size(N_new,2))])

% Print the generated node constraints
disp(['Class K Node constraints:'])
for i=1:numel(node_constraints)
	if numel(node_constraints{i})>1
		disp(['   Coincident nodes: ' num2str(node_constraints{i})])
	end
end
%Specify resting string lengths

% Here, we're setting every string rest length to 70% of its given length
S_0_percent = [(1:size(C_s_new,1))', 1*ones(size(C_s_new,1),1)]; % percent of initial lengths

% S_0_percent(1, 2) = 0.5; % active string should have initial rest length
S_0_percent(2, 2) = 0.5; % stimulation of string 2
% S_0_percent(1, 2) = 0.5; % stimulation of string 1 to (hopefully) ensure stability

% This function converts those specified percentages into rest lengths
s_0 = tenseg_percent2s0(N_new,C_s_new,S_0_percent);

%% Simulation 
% Create data structure of system BEFORE segmentation
classK_test.N = N_new;
classK_test.C_b = C_b_new;
classK_test.C_s = C_s_new;
classK_test.P = P;
classK_test.D = D;
classK_test.s_0 = s_0;
classK_test.tf = 5;
classK_test.dt = .001;
classK_test.video = 0;

%%
% Perform simulation
[History,debug] = tenseg_sim_classkopen(classK_test);

%% Plotting position and velocity of specified node/axes
tenseg_plot_node(History,[1,2,3,4],[1,2,3])
tenseg_plot_velocity(History,[1,2,3,4],[1,2,3])

%% Create plots with 3D objects 
classK_test.Bradius = 0.02; % Radius of bars [# bars x 1]
classK_test.Sradius = [0.01; 0.01]; % Radius of strings [# strings x 1]
classK_test.Nradius = 0.035*ones(size(classK_test.N,2),1); % Radius of node spheres [# nodes x 1]

%% Plotting configurations
number_of_configurations = 3; % Number of configurations to plot
tenseg_plot_configurations(History, classK_test, number_of_configurations)

%% Create animation
% tenseg_animation(History,classK_test,[],[],[],[],10)

% save Example_class_k_Dbar.mat
```

**Comment by ramaniitrgoyal92** [comment]
Hi @waltejon !

You have to mention the mass of the string node in the simulation.
classK_test.ms = 0.1*ones(1,2); % string node point masses. Right now, the simulation is NaN as acceleration is going to infinity.

I accidentally left the default value in the code to be zero, which I have corrected now. My bad!

It should work fine with that. The change was made in : tenseg_defaults.m file, if you want to update it in your repository.


You should be able to use the model-based approach developed in the Control paper to control the structure using this dynamics code. It follows the same formulation.

I hope it helps!

**Comment by waltejon** [comment]
> I accidentally left the default value in the code to be zero, which I have corrected now.

Thank you! With this commit, my configuration is now stable and behaves as expected. Therefore, issue could be closed.

@ramaniitrgoyal92: I still have a few questions regarding the control and the related publication. Would you also be willing to help me with this? Maybe in another issue?
